root = "."
tmp_dir = "tmp"
[build]
  cmd = "make generate && make css && go build -tags fts5 -o ./tmp/main ./cmd/api"
  bin = "./tmp/main"
  exclude_dir = ["assets", "tmp", "vendor", "node_modules", "docs", "storage"]
  include_ext = ["go", "templ", "sql"]
  exclude_regex = ["_templ.go", "internal/db/.*\\.go", "docs/docs.go"]
